// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfwloyrhwhhhdbczrxxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtmd2xveXJod2hoaGRiY3pyeHh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NzYwNzksImV4cCI6MjA3MzM1MjA3OX0.1rr5JwECmlICzwjVIiDO99qscaBhiaBFom8W4296hJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});